name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test
      env:
        GOOFY_USER: foo
        GOOFY_PASS: bar
  
    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy --all-targets --all-features -- -D warnings
        
    - name: Formatting
      run: |
        rustup component add rustfmt
        cargo fmt --check # with --check, rustfmt exits with code 1 if formatting changes are found
